import type {
	LemmaSchemaLanguageShape,
	SelectionSchemaLanguageShape,
} from "../../../registry-shapes";
import {
	GermanAdjectiveInflectionSelectionSchema,
	GermanAdjectiveLemmaSchema,
	GermanAdjectiveLemmaSelectionSchema,
	GermanAdjectiveStandardPartialSelectionSchema,
	GermanAdjectiveStandardVariantSelectionSchema,
	GermanAdjectiveTypoInflectionSelectionSchema,
	GermanAdjectiveTypoLemmaSelectionSchema,
	GermanAdjectiveTypoPartialSelectionSchema,
	GermanAdjectiveTypoVariantSelectionSchema,
} from "./adjective/german-adjective-bundle";
import {
	GermanAdpositionInflectionSelectionSchema,
	GermanAdpositionLemmaSchema,
	GermanAdpositionLemmaSelectionSchema,
	GermanAdpositionStandardPartialSelectionSchema,
	GermanAdpositionStandardVariantSelectionSchema,
	GermanAdpositionTypoInflectionSelectionSchema,
	GermanAdpositionTypoLemmaSelectionSchema,
	GermanAdpositionTypoPartialSelectionSchema,
	GermanAdpositionTypoVariantSelectionSchema,
} from "./adposition/german-adposition-bundle";
import {
	GermanAdverbInflectionSelectionSchema,
	GermanAdverbLemmaSchema,
	GermanAdverbLemmaSelectionSchema,
	GermanAdverbStandardPartialSelectionSchema,
	GermanAdverbStandardVariantSelectionSchema,
	GermanAdverbTypoInflectionSelectionSchema,
	GermanAdverbTypoLemmaSelectionSchema,
	GermanAdverbTypoPartialSelectionSchema,
	GermanAdverbTypoVariantSelectionSchema,
} from "./adverb/german-adverb-bundle";
import {
	GermanAuxiliaryInflectionSelectionSchema,
	GermanAuxiliaryLemmaSchema,
	GermanAuxiliaryLemmaSelectionSchema,
	GermanAuxiliaryStandardPartialSelectionSchema,
	GermanAuxiliaryStandardVariantSelectionSchema,
	GermanAuxiliaryTypoInflectionSelectionSchema,
	GermanAuxiliaryTypoLemmaSelectionSchema,
	GermanAuxiliaryTypoPartialSelectionSchema,
	GermanAuxiliaryTypoVariantSelectionSchema,
} from "./auxiliary/german-auxiliary-bundle";
import {
	GermanCoordinatingConjunctionInflectionSelectionSchema,
	GermanCoordinatingConjunctionLemmaSchema,
	GermanCoordinatingConjunctionLemmaSelectionSchema,
	GermanCoordinatingConjunctionStandardPartialSelectionSchema,
	GermanCoordinatingConjunctionStandardVariantSelectionSchema,
	GermanCoordinatingConjunctionTypoInflectionSelectionSchema,
	GermanCoordinatingConjunctionTypoLemmaSelectionSchema,
	GermanCoordinatingConjunctionTypoPartialSelectionSchema,
	GermanCoordinatingConjunctionTypoVariantSelectionSchema,
} from "./coordinating-conjunction/german-coordinating-conjunction-bundle";
import {
	GermanDeterminerInflectionSelectionSchema,
	GermanDeterminerLemmaSchema,
	GermanDeterminerLemmaSelectionSchema,
	GermanDeterminerStandardPartialSelectionSchema,
	GermanDeterminerStandardVariantSelectionSchema,
	GermanDeterminerTypoInflectionSelectionSchema,
	GermanDeterminerTypoLemmaSelectionSchema,
	GermanDeterminerTypoPartialSelectionSchema,
	GermanDeterminerTypoVariantSelectionSchema,
} from "./determiner/german-determiner-bundle";
import {
	GermanInterjectionInflectionSelectionSchema,
	GermanInterjectionLemmaSchema,
	GermanInterjectionLemmaSelectionSchema,
	GermanInterjectionStandardPartialSelectionSchema,
	GermanInterjectionStandardVariantSelectionSchema,
	GermanInterjectionTypoInflectionSelectionSchema,
	GermanInterjectionTypoLemmaSelectionSchema,
	GermanInterjectionTypoPartialSelectionSchema,
	GermanInterjectionTypoVariantSelectionSchema,
} from "./interjection/german-interjection-bundle";
import {
	GermanNounInflectionSelectionSchema,
	GermanNounLemmaSchema,
	GermanNounLemmaSelectionSchema,
	GermanNounStandardPartialSelectionSchema,
	GermanNounStandardVariantSelectionSchema,
	GermanNounTypoInflectionSelectionSchema,
	GermanNounTypoLemmaSelectionSchema,
	GermanNounTypoPartialSelectionSchema,
	GermanNounTypoVariantSelectionSchema,
} from "./noun/german-noun-bundle";
import {
	GermanNumeralInflectionSelectionSchema,
	GermanNumeralLemmaSchema,
	GermanNumeralLemmaSelectionSchema,
	GermanNumeralStandardPartialSelectionSchema,
	GermanNumeralStandardVariantSelectionSchema,
	GermanNumeralTypoInflectionSelectionSchema,
	GermanNumeralTypoLemmaSelectionSchema,
	GermanNumeralTypoPartialSelectionSchema,
	GermanNumeralTypoVariantSelectionSchema,
} from "./numeral/german-numeral-bundle";
import {
	GermanOtherInflectionSelectionSchema,
	GermanOtherLemmaSchema,
	GermanOtherLemmaSelectionSchema,
	GermanOtherStandardPartialSelectionSchema,
	GermanOtherStandardVariantSelectionSchema,
	GermanOtherTypoInflectionSelectionSchema,
	GermanOtherTypoLemmaSelectionSchema,
	GermanOtherTypoPartialSelectionSchema,
	GermanOtherTypoVariantSelectionSchema,
} from "./other/german-other-bundle";
import {
	GermanParticleInflectionSelectionSchema,
	GermanParticleLemmaSchema,
	GermanParticleLemmaSelectionSchema,
	GermanParticleStandardPartialSelectionSchema,
	GermanParticleStandardVariantSelectionSchema,
	GermanParticleTypoInflectionSelectionSchema,
	GermanParticleTypoLemmaSelectionSchema,
	GermanParticleTypoPartialSelectionSchema,
	GermanParticleTypoVariantSelectionSchema,
} from "./particle/german-particle-bundle";
import {
	GermanPronounInflectionSelectionSchema,
	GermanPronounLemmaSchema,
	GermanPronounLemmaSelectionSchema,
	GermanPronounStandardPartialSelectionSchema,
	GermanPronounStandardVariantSelectionSchema,
	GermanPronounTypoInflectionSelectionSchema,
	GermanPronounTypoLemmaSelectionSchema,
	GermanPronounTypoPartialSelectionSchema,
	GermanPronounTypoVariantSelectionSchema,
} from "./pronoun/german-pronoun-bundle";
import {
	GermanProperNounInflectionSelectionSchema,
	GermanProperNounLemmaSchema,
	GermanProperNounLemmaSelectionSchema,
	GermanProperNounStandardPartialSelectionSchema,
	GermanProperNounStandardVariantSelectionSchema,
	GermanProperNounTypoInflectionSelectionSchema,
	GermanProperNounTypoLemmaSelectionSchema,
	GermanProperNounTypoPartialSelectionSchema,
	GermanProperNounTypoVariantSelectionSchema,
} from "./proper-noun/german-proper-noun-bundle";
import {
	GermanPunctuationInflectionSelectionSchema,
	GermanPunctuationLemmaSchema,
	GermanPunctuationLemmaSelectionSchema,
	GermanPunctuationStandardPartialSelectionSchema,
	GermanPunctuationStandardVariantSelectionSchema,
	GermanPunctuationTypoInflectionSelectionSchema,
	GermanPunctuationTypoLemmaSelectionSchema,
	GermanPunctuationTypoPartialSelectionSchema,
	GermanPunctuationTypoVariantSelectionSchema,
} from "./punctuation/german-punctuation-bundle";
import {
	GermanSubordinatingConjunctionInflectionSelectionSchema,
	GermanSubordinatingConjunctionLemmaSchema,
	GermanSubordinatingConjunctionLemmaSelectionSchema,
	GermanSubordinatingConjunctionStandardPartialSelectionSchema,
	GermanSubordinatingConjunctionStandardVariantSelectionSchema,
	GermanSubordinatingConjunctionTypoInflectionSelectionSchema,
	GermanSubordinatingConjunctionTypoLemmaSelectionSchema,
	GermanSubordinatingConjunctionTypoPartialSelectionSchema,
	GermanSubordinatingConjunctionTypoVariantSelectionSchema,
} from "./subordinating-conjunction/german-subordinating-conjunction-bundle";
import {
	GermanSymbolInflectionSelectionSchema,
	GermanSymbolLemmaSchema,
	GermanSymbolLemmaSelectionSchema,
	GermanSymbolStandardPartialSelectionSchema,
	GermanSymbolStandardVariantSelectionSchema,
	GermanSymbolTypoInflectionSelectionSchema,
	GermanSymbolTypoLemmaSelectionSchema,
	GermanSymbolTypoPartialSelectionSchema,
	GermanSymbolTypoVariantSelectionSchema,
} from "./symbol/german-symbol-bundle";
import {
	GermanVerbInflectionSelectionSchema,
	GermanVerbLemmaSchema,
	GermanVerbLemmaSelectionSchema,
	GermanVerbStandardPartialSelectionSchema,
	GermanVerbStandardVariantSelectionSchema,
	GermanVerbTypoInflectionSelectionSchema,
	GermanVerbTypoLemmaSelectionSchema,
	GermanVerbTypoPartialSelectionSchema,
	GermanVerbTypoVariantSelectionSchema,
} from "./verb/german-verb-bundle";

export const GermanLexemeLemmaSchemas = {
	ADJ: GermanAdjectiveLemmaSchema,
	ADP: GermanAdpositionLemmaSchema,
	ADV: GermanAdverbLemmaSchema,
	AUX: GermanAuxiliaryLemmaSchema,
	CCONJ: GermanCoordinatingConjunctionLemmaSchema,
	DET: GermanDeterminerLemmaSchema,
	INTJ: GermanInterjectionLemmaSchema,
	NOUN: GermanNounLemmaSchema,
	NUM: GermanNumeralLemmaSchema,
	PART: GermanParticleLemmaSchema,
	PRON: GermanPronounLemmaSchema,
	PROPN: GermanProperNounLemmaSchema,
	PUNCT: GermanPunctuationLemmaSchema,
	SCONJ: GermanSubordinatingConjunctionLemmaSchema,
	SYM: GermanSymbolLemmaSchema,
	VERB: GermanVerbLemmaSchema,
	X: GermanOtherLemmaSchema,
} satisfies LemmaSchemaLanguageShape["Lexeme"];

export const GermanStandardInflectionLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveInflectionSelectionSchema,
	ADP: GermanAdpositionInflectionSelectionSchema,
	ADV: GermanAdverbInflectionSelectionSchema,
	AUX: GermanAuxiliaryInflectionSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionInflectionSelectionSchema,
	DET: GermanDeterminerInflectionSelectionSchema,
	INTJ: GermanInterjectionInflectionSelectionSchema,
	NOUN: GermanNounInflectionSelectionSchema,
	NUM: GermanNumeralInflectionSelectionSchema,
	PART: GermanParticleInflectionSelectionSchema,
	PRON: GermanPronounInflectionSelectionSchema,
	PROPN: GermanProperNounInflectionSelectionSchema,
	PUNCT: GermanPunctuationInflectionSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionInflectionSelectionSchema,
	SYM: GermanSymbolInflectionSelectionSchema,
	VERB: GermanVerbInflectionSelectionSchema,
	X: GermanOtherInflectionSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Inflection"]["Lexeme"];

export const GermanStandardLemmaLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveLemmaSelectionSchema,
	ADP: GermanAdpositionLemmaSelectionSchema,
	ADV: GermanAdverbLemmaSelectionSchema,
	AUX: GermanAuxiliaryLemmaSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionLemmaSelectionSchema,
	DET: GermanDeterminerLemmaSelectionSchema,
	INTJ: GermanInterjectionLemmaSelectionSchema,
	NOUN: GermanNounLemmaSelectionSchema,
	NUM: GermanNumeralLemmaSelectionSchema,
	PART: GermanParticleLemmaSelectionSchema,
	PRON: GermanPronounLemmaSelectionSchema,
	PROPN: GermanProperNounLemmaSelectionSchema,
	PUNCT: GermanPunctuationLemmaSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionLemmaSelectionSchema,
	SYM: GermanSymbolLemmaSelectionSchema,
	VERB: GermanVerbLemmaSelectionSchema,
	X: GermanOtherLemmaSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Lemma"]["Lexeme"];

export const GermanStandardPartialLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveStandardPartialSelectionSchema,
	ADP: GermanAdpositionStandardPartialSelectionSchema,
	ADV: GermanAdverbStandardPartialSelectionSchema,
	AUX: GermanAuxiliaryStandardPartialSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionStandardPartialSelectionSchema,
	DET: GermanDeterminerStandardPartialSelectionSchema,
	INTJ: GermanInterjectionStandardPartialSelectionSchema,
	NOUN: GermanNounStandardPartialSelectionSchema,
	NUM: GermanNumeralStandardPartialSelectionSchema,
	PART: GermanParticleStandardPartialSelectionSchema,
	PRON: GermanPronounStandardPartialSelectionSchema,
	PROPN: GermanProperNounStandardPartialSelectionSchema,
	PUNCT: GermanPunctuationStandardPartialSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionStandardPartialSelectionSchema,
	SYM: GermanSymbolStandardPartialSelectionSchema,
	VERB: GermanVerbStandardPartialSelectionSchema,
	X: GermanOtherStandardPartialSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Partial"]["Lexeme"];

export const GermanStandardVariantLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveStandardVariantSelectionSchema,
	ADP: GermanAdpositionStandardVariantSelectionSchema,
	ADV: GermanAdverbStandardVariantSelectionSchema,
	AUX: GermanAuxiliaryStandardVariantSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionStandardVariantSelectionSchema,
	DET: GermanDeterminerStandardVariantSelectionSchema,
	INTJ: GermanInterjectionStandardVariantSelectionSchema,
	NOUN: GermanNounStandardVariantSelectionSchema,
	NUM: GermanNumeralStandardVariantSelectionSchema,
	PART: GermanParticleStandardVariantSelectionSchema,
	PRON: GermanPronounStandardVariantSelectionSchema,
	PROPN: GermanProperNounStandardVariantSelectionSchema,
	PUNCT: GermanPunctuationStandardVariantSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionStandardVariantSelectionSchema,
	SYM: GermanSymbolStandardVariantSelectionSchema,
	VERB: GermanVerbStandardVariantSelectionSchema,
	X: GermanOtherStandardVariantSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Variant"]["Lexeme"];

export const GermanTypoInflectionLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoInflectionSelectionSchema,
	ADP: GermanAdpositionTypoInflectionSelectionSchema,
	ADV: GermanAdverbTypoInflectionSelectionSchema,
	AUX: GermanAuxiliaryTypoInflectionSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoInflectionSelectionSchema,
	DET: GermanDeterminerTypoInflectionSelectionSchema,
	INTJ: GermanInterjectionTypoInflectionSelectionSchema,
	NOUN: GermanNounTypoInflectionSelectionSchema,
	NUM: GermanNumeralTypoInflectionSelectionSchema,
	PART: GermanParticleTypoInflectionSelectionSchema,
	PRON: GermanPronounTypoInflectionSelectionSchema,
	PROPN: GermanProperNounTypoInflectionSelectionSchema,
	PUNCT: GermanPunctuationTypoInflectionSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoInflectionSelectionSchema,
	SYM: GermanSymbolTypoInflectionSelectionSchema,
	VERB: GermanVerbTypoInflectionSelectionSchema,
	X: GermanOtherTypoInflectionSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Inflection"]["Lexeme"];

export const GermanTypoLemmaLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoLemmaSelectionSchema,
	ADP: GermanAdpositionTypoLemmaSelectionSchema,
	ADV: GermanAdverbTypoLemmaSelectionSchema,
	AUX: GermanAuxiliaryTypoLemmaSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoLemmaSelectionSchema,
	DET: GermanDeterminerTypoLemmaSelectionSchema,
	INTJ: GermanInterjectionTypoLemmaSelectionSchema,
	NOUN: GermanNounTypoLemmaSelectionSchema,
	NUM: GermanNumeralTypoLemmaSelectionSchema,
	PART: GermanParticleTypoLemmaSelectionSchema,
	PRON: GermanPronounTypoLemmaSelectionSchema,
	PROPN: GermanProperNounTypoLemmaSelectionSchema,
	PUNCT: GermanPunctuationTypoLemmaSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoLemmaSelectionSchema,
	SYM: GermanSymbolTypoLemmaSelectionSchema,
	VERB: GermanVerbTypoLemmaSelectionSchema,
	X: GermanOtherTypoLemmaSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Lemma"]["Lexeme"];

export const GermanTypoPartialLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoPartialSelectionSchema,
	ADP: GermanAdpositionTypoPartialSelectionSchema,
	ADV: GermanAdverbTypoPartialSelectionSchema,
	AUX: GermanAuxiliaryTypoPartialSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoPartialSelectionSchema,
	DET: GermanDeterminerTypoPartialSelectionSchema,
	INTJ: GermanInterjectionTypoPartialSelectionSchema,
	NOUN: GermanNounTypoPartialSelectionSchema,
	NUM: GermanNumeralTypoPartialSelectionSchema,
	PART: GermanParticleTypoPartialSelectionSchema,
	PRON: GermanPronounTypoPartialSelectionSchema,
	PROPN: GermanProperNounTypoPartialSelectionSchema,
	PUNCT: GermanPunctuationTypoPartialSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoPartialSelectionSchema,
	SYM: GermanSymbolTypoPartialSelectionSchema,
	VERB: GermanVerbTypoPartialSelectionSchema,
	X: GermanOtherTypoPartialSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Partial"]["Lexeme"];

export const GermanTypoVariantLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoVariantSelectionSchema,
	ADP: GermanAdpositionTypoVariantSelectionSchema,
	ADV: GermanAdverbTypoVariantSelectionSchema,
	AUX: GermanAuxiliaryTypoVariantSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoVariantSelectionSchema,
	DET: GermanDeterminerTypoVariantSelectionSchema,
	INTJ: GermanInterjectionTypoVariantSelectionSchema,
	NOUN: GermanNounTypoVariantSelectionSchema,
	NUM: GermanNumeralTypoVariantSelectionSchema,
	PART: GermanParticleTypoVariantSelectionSchema,
	PRON: GermanPronounTypoVariantSelectionSchema,
	PROPN: GermanProperNounTypoVariantSelectionSchema,
	PUNCT: GermanPunctuationTypoVariantSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoVariantSelectionSchema,
	SYM: GermanSymbolTypoVariantSelectionSchema,
	VERB: GermanVerbTypoVariantSelectionSchema,
	X: GermanOtherTypoVariantSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Variant"]["Lexeme"];
