import z from "zod/v3";
import type { SelectionSchemaLanguageShape } from "../registry-shapes";
import type { AbstractSelectionFor } from "../universal/abstract-selection";
import {
	GermanAdjectiveInflectionSelectionSchema,
	GermanAdjectiveLemmaSelectionSchema,
	GermanAdjectiveStandardPartialSelectionSchema,
	GermanAdjectiveStandardVariantSelectionSchema,
	GermanAdjectiveTypoInflectionSelectionSchema,
	GermanAdjectiveTypoLemmaSelectionSchema,
	GermanAdjectiveTypoPartialSelectionSchema,
	GermanAdjectiveTypoVariantSelectionSchema,
} from "./lu/lexeme/adjective/german-adjective-bundle";
import {
	GermanAdpositionInflectionSelectionSchema,
	GermanAdpositionLemmaSelectionSchema,
	GermanAdpositionStandardPartialSelectionSchema,
	GermanAdpositionStandardVariantSelectionSchema,
	GermanAdpositionTypoInflectionSelectionSchema,
	GermanAdpositionTypoLemmaSelectionSchema,
	GermanAdpositionTypoPartialSelectionSchema,
	GermanAdpositionTypoVariantSelectionSchema,
} from "./lu/lexeme/adposition/german-adposition-bundle";
import {
	GermanAdverbInflectionSelectionSchema,
	GermanAdverbLemmaSelectionSchema,
	GermanAdverbStandardPartialSelectionSchema,
	GermanAdverbStandardVariantSelectionSchema,
	GermanAdverbTypoInflectionSelectionSchema,
	GermanAdverbTypoLemmaSelectionSchema,
	GermanAdverbTypoPartialSelectionSchema,
	GermanAdverbTypoVariantSelectionSchema,
} from "./lu/lexeme/adverb/german-adverb-bundle";
import {
	GermanAuxiliaryInflectionSelectionSchema,
	GermanAuxiliaryLemmaSelectionSchema,
	GermanAuxiliaryStandardPartialSelectionSchema,
	GermanAuxiliaryStandardVariantSelectionSchema,
	GermanAuxiliaryTypoInflectionSelectionSchema,
	GermanAuxiliaryTypoLemmaSelectionSchema,
	GermanAuxiliaryTypoPartialSelectionSchema,
	GermanAuxiliaryTypoVariantSelectionSchema,
} from "./lu/lexeme/auxiliary/german-auxiliary-bundle";
import {
	GermanCoordinatingConjunctionInflectionSelectionSchema,
	GermanCoordinatingConjunctionLemmaSelectionSchema,
	GermanCoordinatingConjunctionStandardPartialSelectionSchema,
	GermanCoordinatingConjunctionStandardVariantSelectionSchema,
	GermanCoordinatingConjunctionTypoInflectionSelectionSchema,
	GermanCoordinatingConjunctionTypoLemmaSelectionSchema,
	GermanCoordinatingConjunctionTypoPartialSelectionSchema,
	GermanCoordinatingConjunctionTypoVariantSelectionSchema,
} from "./lu/lexeme/coordinating-conjunction/german-coordinating-conjunction-bundle";
import {
	GermanDeterminerInflectionSelectionSchema,
	GermanDeterminerLemmaSelectionSchema,
	GermanDeterminerStandardPartialSelectionSchema,
	GermanDeterminerStandardVariantSelectionSchema,
	GermanDeterminerTypoInflectionSelectionSchema,
	GermanDeterminerTypoLemmaSelectionSchema,
	GermanDeterminerTypoPartialSelectionSchema,
	GermanDeterminerTypoVariantSelectionSchema,
} from "./lu/lexeme/determiner/german-determiner-bundle";
import {
	GermanInterjectionInflectionSelectionSchema,
	GermanInterjectionLemmaSelectionSchema,
	GermanInterjectionStandardPartialSelectionSchema,
	GermanInterjectionStandardVariantSelectionSchema,
	GermanInterjectionTypoInflectionSelectionSchema,
	GermanInterjectionTypoLemmaSelectionSchema,
	GermanInterjectionTypoPartialSelectionSchema,
	GermanInterjectionTypoVariantSelectionSchema,
} from "./lu/lexeme/interjection/german-interjection-bundle";
import {
	GermanNounInflectionSelectionSchema,
	GermanNounLemmaSelectionSchema,
	GermanNounStandardPartialSelectionSchema,
	GermanNounStandardVariantSelectionSchema,
	GermanNounTypoInflectionSelectionSchema,
	GermanNounTypoLemmaSelectionSchema,
	GermanNounTypoPartialSelectionSchema,
	GermanNounTypoVariantSelectionSchema,
} from "./lu/lexeme/noun/german-noun-bundle";
import {
	GermanNumeralInflectionSelectionSchema,
	GermanNumeralLemmaSelectionSchema,
	GermanNumeralStandardPartialSelectionSchema,
	GermanNumeralStandardVariantSelectionSchema,
	GermanNumeralTypoInflectionSelectionSchema,
	GermanNumeralTypoLemmaSelectionSchema,
	GermanNumeralTypoPartialSelectionSchema,
	GermanNumeralTypoVariantSelectionSchema,
} from "./lu/lexeme/numeral/german-numeral-bundle";
import {
	GermanOtherInflectionSelectionSchema,
	GermanOtherLemmaSelectionSchema,
	GermanOtherStandardPartialSelectionSchema,
	GermanOtherStandardVariantSelectionSchema,
	GermanOtherTypoInflectionSelectionSchema,
	GermanOtherTypoLemmaSelectionSchema,
	GermanOtherTypoPartialSelectionSchema,
	GermanOtherTypoVariantSelectionSchema,
} from "./lu/lexeme/other/german-other-bundle";
import {
	GermanParticleInflectionSelectionSchema,
	GermanParticleLemmaSelectionSchema,
	GermanParticleStandardPartialSelectionSchema,
	GermanParticleStandardVariantSelectionSchema,
	GermanParticleTypoInflectionSelectionSchema,
	GermanParticleTypoLemmaSelectionSchema,
	GermanParticleTypoPartialSelectionSchema,
	GermanParticleTypoVariantSelectionSchema,
} from "./lu/lexeme/particle/german-particle-bundle";
import {
	GermanPronounInflectionSelectionSchema,
	GermanPronounLemmaSelectionSchema,
	GermanPronounStandardPartialSelectionSchema,
	GermanPronounStandardVariantSelectionSchema,
	GermanPronounTypoInflectionSelectionSchema,
	GermanPronounTypoLemmaSelectionSchema,
	GermanPronounTypoPartialSelectionSchema,
	GermanPronounTypoVariantSelectionSchema,
} from "./lu/lexeme/pronoun/german-pronoun-bundle";
import {
	GermanProperNounInflectionSelectionSchema,
	GermanProperNounLemmaSelectionSchema,
	GermanProperNounStandardPartialSelectionSchema,
	GermanProperNounStandardVariantSelectionSchema,
	GermanProperNounTypoInflectionSelectionSchema,
	GermanProperNounTypoLemmaSelectionSchema,
	GermanProperNounTypoPartialSelectionSchema,
	GermanProperNounTypoVariantSelectionSchema,
} from "./lu/lexeme/proper-noun/german-proper-noun-bundle";
import {
	GermanPunctuationInflectionSelectionSchema,
	GermanPunctuationLemmaSelectionSchema,
	GermanPunctuationStandardPartialSelectionSchema,
	GermanPunctuationStandardVariantSelectionSchema,
	GermanPunctuationTypoInflectionSelectionSchema,
	GermanPunctuationTypoLemmaSelectionSchema,
	GermanPunctuationTypoPartialSelectionSchema,
	GermanPunctuationTypoVariantSelectionSchema,
} from "./lu/lexeme/punctuation/german-punctuation-bundle";
import {
	GermanSubordinatingConjunctionInflectionSelectionSchema,
	GermanSubordinatingConjunctionLemmaSelectionSchema,
	GermanSubordinatingConjunctionStandardPartialSelectionSchema,
	GermanSubordinatingConjunctionStandardVariantSelectionSchema,
	GermanSubordinatingConjunctionTypoInflectionSelectionSchema,
	GermanSubordinatingConjunctionTypoLemmaSelectionSchema,
	GermanSubordinatingConjunctionTypoPartialSelectionSchema,
	GermanSubordinatingConjunctionTypoVariantSelectionSchema,
} from "./lu/lexeme/subordinating-conjunction/german-subordinating-conjunction-bundle";
import {
	GermanSymbolInflectionSelectionSchema,
	GermanSymbolLemmaSelectionSchema,
	GermanSymbolStandardPartialSelectionSchema,
	GermanSymbolStandardVariantSelectionSchema,
	GermanSymbolTypoInflectionSelectionSchema,
	GermanSymbolTypoLemmaSelectionSchema,
	GermanSymbolTypoPartialSelectionSchema,
	GermanSymbolTypoVariantSelectionSchema,
} from "./lu/lexeme/symbol/german-symbol-bundle";
import {
	GermanVerbInflectionSelectionSchema,
	GermanVerbLemmaSelectionSchema,
	GermanVerbStandardPartialSelectionSchema,
	GermanVerbStandardVariantSelectionSchema,
	GermanVerbTypoInflectionSelectionSchema,
	GermanVerbTypoLemmaSelectionSchema,
	GermanVerbTypoPartialSelectionSchema,
	GermanVerbTypoVariantSelectionSchema,
} from "./lu/lexeme/verb/german-verb-bundle";

const AnySchema = z.any();
const GermanUnknownSelectionSchema = z.object({
	orthographicStatus: z.literal("Unknown"),
}) satisfies z.ZodType<AbstractSelectionFor<"Unknown">>;
const GermanStandardInflectionLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveInflectionSelectionSchema,
	ADP: GermanAdpositionInflectionSelectionSchema,
	ADV: GermanAdverbInflectionSelectionSchema,
	AUX: GermanAuxiliaryInflectionSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionInflectionSelectionSchema,
	DET: GermanDeterminerInflectionSelectionSchema,
	INTJ: GermanInterjectionInflectionSelectionSchema,
	NOUN: GermanNounInflectionSelectionSchema,
	NUM: GermanNumeralInflectionSelectionSchema,
	PART: GermanParticleInflectionSelectionSchema,
	PRON: GermanPronounInflectionSelectionSchema,
	PROPN: GermanProperNounInflectionSelectionSchema,
	PUNCT: GermanPunctuationInflectionSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionInflectionSelectionSchema,
	SYM: GermanSymbolInflectionSelectionSchema,
	VERB: GermanVerbInflectionSelectionSchema,
	X: GermanOtherInflectionSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Inflection"]["Lexeme"];
const GermanStandardLemmaLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveLemmaSelectionSchema,
	ADP: GermanAdpositionLemmaSelectionSchema,
	ADV: GermanAdverbLemmaSelectionSchema,
	AUX: GermanAuxiliaryLemmaSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionLemmaSelectionSchema,
	DET: GermanDeterminerLemmaSelectionSchema,
	INTJ: GermanInterjectionLemmaSelectionSchema,
	NOUN: GermanNounLemmaSelectionSchema,
	NUM: GermanNumeralLemmaSelectionSchema,
	PART: GermanParticleLemmaSelectionSchema,
	PRON: GermanPronounLemmaSelectionSchema,
	PROPN: GermanProperNounLemmaSelectionSchema,
	PUNCT: GermanPunctuationLemmaSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionLemmaSelectionSchema,
	SYM: GermanSymbolLemmaSelectionSchema,
	VERB: GermanVerbLemmaSelectionSchema,
	X: GermanOtherLemmaSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Lemma"]["Lexeme"];
const GermanStandardPartialLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveStandardPartialSelectionSchema,
	ADP: GermanAdpositionStandardPartialSelectionSchema,
	ADV: GermanAdverbStandardPartialSelectionSchema,
	AUX: GermanAuxiliaryStandardPartialSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionStandardPartialSelectionSchema,
	DET: GermanDeterminerStandardPartialSelectionSchema,
	INTJ: GermanInterjectionStandardPartialSelectionSchema,
	NOUN: GermanNounStandardPartialSelectionSchema,
	NUM: GermanNumeralStandardPartialSelectionSchema,
	PART: GermanParticleStandardPartialSelectionSchema,
	PRON: GermanPronounStandardPartialSelectionSchema,
	PROPN: GermanProperNounStandardPartialSelectionSchema,
	PUNCT: GermanPunctuationStandardPartialSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionStandardPartialSelectionSchema,
	SYM: GermanSymbolStandardPartialSelectionSchema,
	VERB: GermanVerbStandardPartialSelectionSchema,
	X: GermanOtherStandardPartialSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Partial"]["Lexeme"];
const GermanStandardVariantLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveStandardVariantSelectionSchema,
	ADP: GermanAdpositionStandardVariantSelectionSchema,
	ADV: GermanAdverbStandardVariantSelectionSchema,
	AUX: GermanAuxiliaryStandardVariantSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionStandardVariantSelectionSchema,
	DET: GermanDeterminerStandardVariantSelectionSchema,
	INTJ: GermanInterjectionStandardVariantSelectionSchema,
	NOUN: GermanNounStandardVariantSelectionSchema,
	NUM: GermanNumeralStandardVariantSelectionSchema,
	PART: GermanParticleStandardVariantSelectionSchema,
	PRON: GermanPronounStandardVariantSelectionSchema,
	PROPN: GermanProperNounStandardVariantSelectionSchema,
	PUNCT: GermanPunctuationStandardVariantSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionStandardVariantSelectionSchema,
	SYM: GermanSymbolStandardVariantSelectionSchema,
	VERB: GermanVerbStandardVariantSelectionSchema,
	X: GermanOtherStandardVariantSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Variant"]["Lexeme"];
const GermanTypoInflectionLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoInflectionSelectionSchema,
	ADP: GermanAdpositionTypoInflectionSelectionSchema,
	ADV: GermanAdverbTypoInflectionSelectionSchema,
	AUX: GermanAuxiliaryTypoInflectionSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoInflectionSelectionSchema,
	DET: GermanDeterminerTypoInflectionSelectionSchema,
	INTJ: GermanInterjectionTypoInflectionSelectionSchema,
	NOUN: GermanNounTypoInflectionSelectionSchema,
	NUM: GermanNumeralTypoInflectionSelectionSchema,
	PART: GermanParticleTypoInflectionSelectionSchema,
	PRON: GermanPronounTypoInflectionSelectionSchema,
	PROPN: GermanProperNounTypoInflectionSelectionSchema,
	PUNCT: GermanPunctuationTypoInflectionSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoInflectionSelectionSchema,
	SYM: GermanSymbolTypoInflectionSelectionSchema,
	VERB: GermanVerbTypoInflectionSelectionSchema,
	X: GermanOtherTypoInflectionSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Inflection"]["Lexeme"];
const GermanTypoLemmaLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoLemmaSelectionSchema,
	ADP: GermanAdpositionTypoLemmaSelectionSchema,
	ADV: GermanAdverbTypoLemmaSelectionSchema,
	AUX: GermanAuxiliaryTypoLemmaSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoLemmaSelectionSchema,
	DET: GermanDeterminerTypoLemmaSelectionSchema,
	INTJ: GermanInterjectionTypoLemmaSelectionSchema,
	NOUN: GermanNounTypoLemmaSelectionSchema,
	NUM: GermanNumeralTypoLemmaSelectionSchema,
	PART: GermanParticleTypoLemmaSelectionSchema,
	PRON: GermanPronounTypoLemmaSelectionSchema,
	PROPN: GermanProperNounTypoLemmaSelectionSchema,
	PUNCT: GermanPunctuationTypoLemmaSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoLemmaSelectionSchema,
	SYM: GermanSymbolTypoLemmaSelectionSchema,
	VERB: GermanVerbTypoLemmaSelectionSchema,
	X: GermanOtherTypoLemmaSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Lemma"]["Lexeme"];
const GermanTypoPartialLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoPartialSelectionSchema,
	ADP: GermanAdpositionTypoPartialSelectionSchema,
	ADV: GermanAdverbTypoPartialSelectionSchema,
	AUX: GermanAuxiliaryTypoPartialSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoPartialSelectionSchema,
	DET: GermanDeterminerTypoPartialSelectionSchema,
	INTJ: GermanInterjectionTypoPartialSelectionSchema,
	NOUN: GermanNounTypoPartialSelectionSchema,
	NUM: GermanNumeralTypoPartialSelectionSchema,
	PART: GermanParticleTypoPartialSelectionSchema,
	PRON: GermanPronounTypoPartialSelectionSchema,
	PROPN: GermanProperNounTypoPartialSelectionSchema,
	PUNCT: GermanPunctuationTypoPartialSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoPartialSelectionSchema,
	SYM: GermanSymbolTypoPartialSelectionSchema,
	VERB: GermanVerbTypoPartialSelectionSchema,
	X: GermanOtherTypoPartialSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Partial"]["Lexeme"];
const GermanTypoVariantLexemeSelectionSchemas = {
	ADJ: GermanAdjectiveTypoVariantSelectionSchema,
	ADP: GermanAdpositionTypoVariantSelectionSchema,
	ADV: GermanAdverbTypoVariantSelectionSchema,
	AUX: GermanAuxiliaryTypoVariantSelectionSchema,
	CCONJ: GermanCoordinatingConjunctionTypoVariantSelectionSchema,
	DET: GermanDeterminerTypoVariantSelectionSchema,
	INTJ: GermanInterjectionTypoVariantSelectionSchema,
	NOUN: GermanNounTypoVariantSelectionSchema,
	NUM: GermanNumeralTypoVariantSelectionSchema,
	PART: GermanParticleTypoVariantSelectionSchema,
	PRON: GermanPronounTypoVariantSelectionSchema,
	PROPN: GermanProperNounTypoVariantSelectionSchema,
	PUNCT: GermanPunctuationTypoVariantSelectionSchema,
	SCONJ: GermanSubordinatingConjunctionTypoVariantSelectionSchema,
	SYM: GermanSymbolTypoVariantSelectionSchema,
	VERB: GermanVerbTypoVariantSelectionSchema,
	X: GermanOtherTypoVariantSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Variant"]["Lexeme"];

export const GermanSelectionSchema = {
	Standard: {
		Inflection: {
			Lexeme: GermanStandardInflectionLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Lemma: {
			Lexeme: GermanStandardLemmaLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Partial: {
			Lexeme: GermanStandardPartialLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Variant: {
			Lexeme: GermanStandardVariantLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
	},
	Typo: {
		Inflection: {
			Lexeme: GermanTypoInflectionLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Lemma: {
			Lexeme: GermanTypoLemmaLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Partial: {
			Lexeme: GermanTypoPartialLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Variant: {
			Lexeme: GermanTypoVariantLexemeSelectionSchemas,
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
	},
	Unknown: GermanUnknownSelectionSchema,
} satisfies SelectionSchemaLanguageShape;
