import z from "zod/v3";
import type { SelectionSchemaLanguageShape } from "../registry-shapes";
import {
	GermanVerbInflectionSelectionSchema,
	GermanVerbLemmaSelectionSchema,
	GermanVerbStandardPartialSelectionSchema,
	GermanVerbStandardVariantSelectionSchema,
	GermanVerbTypoInflectionSelectionSchema,
	GermanVerbTypoLemmaSelectionSchema,
	GermanVerbTypoPartialSelectionSchema,
	GermanVerbTypoVariantSelectionSchema,
	GermanVerbUnknownSelectionSchema,
} from "./lu/lexeme/pos/german-verb";

const AnySchema = z.any();

export const GermanSelectionSchema = {
	Standard: {
		Inflection: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbInflectionSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Lemma: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbLemmaSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Partial: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbStandardPartialSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Variant: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbStandardVariantSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
	},
	Typo: {
		Inflection: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbTypoInflectionSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Lemma: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbTypoLemmaSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Partial: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbTypoPartialSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Variant: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbTypoVariantSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
	},
	Unknown: {
		Inflection: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbUnknownSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Lemma: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbUnknownSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Partial: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbUnknownSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
		Variant: {
			Lexeme: {
				ADJ: AnySchema,
				ADP: AnySchema,
				ADV: AnySchema,
				AUX: AnySchema,
				CCONJ: AnySchema,
				DET: AnySchema,
				INTJ: AnySchema,
				NOUN: AnySchema,
				NUM: AnySchema,
				PART: AnySchema,
				PRON: AnySchema,
				PROPN: AnySchema,
				PUNCT: AnySchema,
				SCONJ: AnySchema,
				SYM: AnySchema,
				VERB: GermanVerbUnknownSelectionSchema,
				X: AnySchema,
			},
			Morpheme: {
				Circumfix: AnySchema,
				Clitic: AnySchema,
				Duplifix: AnySchema,
				Infix: AnySchema,
				Interfix: AnySchema,
				Prefix: AnySchema,
				Root: AnySchema,
				Suffix: AnySchema,
				Suffixoid: AnySchema,
				ToneMarking: AnySchema,
				Transfix: AnySchema,
			},
			Phraseme: {
				Aphorism: AnySchema,
				Cliché: AnySchema,
				DiscourseFormula: AnySchema,
			},
		},
	},
} satisfies SelectionSchemaLanguageShape;
