export {
	LEXICAL_PHRASEME_KIND_VALUES,
	LEXICAL_POS_VALUES,
	LexicalCaseSchema,
	LexicalLinguisticUnitKindSchema,
	LexicalMorphemeKindSchema,
	LexicalNumberSchema,
	LexicalPhrasemeKindSchema,
	LexicalPosSchema,
	LexicalSurfaceKindSchema,
} from "@textfresser/linguistics/common";
export {
	LexicalAdjectiveClassificationSchema,
	LexicalAdjectiveDistributionSchema,
	LexicalAdjectiveGovernedPatternSchema,
	LexicalAdjectiveGradabilitySchema,
	LexicalAdjectiveValencySchema,
	LexicalGenusSchema,
	LexicalNounClassSchema,
	LexicalVerbConjugationSchema,
	LexicalVerbReflexivitySchema,
	LexicalVerbSeparabilitySchema,
	LexicalVerbValencySchema,
	SeparabilitySchema,
} from "@textfresser/linguistics/de/schema-primitives";
