export {
	LEXICAL_PHRASEME_KIND_VALUES,
	LEXICAL_POS_VALUES,
	LexicalAdjectiveClassificationSchema,
	LexicalAdjectiveDistributionSchema,
	LexicalAdjectiveGovernedPatternSchema,
	LexicalAdjectiveGradabilitySchema,
	LexicalAdjectiveValencySchema,
	LexicalCaseSchema,
	LexicalGenusSchema,
	LexicalLinguisticUnitKindSchema,
	LexicalMorphemeKindSchema,
	LexicalNounClassSchema,
	LexicalNumberSchema,
	LexicalPhrasemeKindSchema,
	LexicalPosSchema,
	LexicalSurfaceKindSchema,
	LexicalVerbConjugationSchema,
	LexicalVerbReflexivitySchema,
	LexicalVerbSeparabilitySchema,
	LexicalVerbValencySchema,
	SeparabilitySchema,
} from "./legacy-linguistics";
