import { buildEnglishLexemeBundle } from "../shared/build-english-lexeme-bundle";
import {
	EnglishSubordinatingConjunctionInflectionalFeaturesSchema,
	EnglishSubordinatingConjunctionInherentFeaturesSchema,
} from "./parts/english-subordinating-conjunction-features";
import {
	EnglishSubordinatingConjunctionLexicalRelationsSchema,
	EnglishSubordinatingConjunctionMorphologicalRelationsSchema,
} from "./parts/english-subordinating-conjunction-relations";

const EnglishSubordinatingConjunctionSchemas = buildEnglishLexemeBundle({
	inflectionalFeaturesSchema:
		EnglishSubordinatingConjunctionInflectionalFeaturesSchema,
	inherentFeaturesSchema:
		EnglishSubordinatingConjunctionInherentFeaturesSchema,
	lexicalRelationsSchema:
		EnglishSubordinatingConjunctionLexicalRelationsSchema,
	morphologicalRelationsSchema:
		EnglishSubordinatingConjunctionMorphologicalRelationsSchema,
	pos: "SCONJ",
});

export const EnglishSubordinatingConjunctionInflectionSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.InflectionSelectionSchema;
export const EnglishSubordinatingConjunctionLemmaSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.LemmaSelectionSchema;
export const EnglishSubordinatingConjunctionStandardPartialSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.StandardPartialSelectionSchema;
export const EnglishSubordinatingConjunctionStandardVariantSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.StandardVariantSelectionSchema;
export const EnglishSubordinatingConjunctionTypoInflectionSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.TypoInflectionSelectionSchema;
export const EnglishSubordinatingConjunctionTypoLemmaSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.TypoLemmaSelectionSchema;
export const EnglishSubordinatingConjunctionTypoPartialSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.TypoPartialSelectionSchema;
export const EnglishSubordinatingConjunctionTypoVariantSelectionSchema =
	EnglishSubordinatingConjunctionSchemas.TypoVariantSelectionSchema;
export const EnglishSubordinatingConjunctionLemmaSchema =
	EnglishSubordinatingConjunctionSchemas.LemmaSchema;
