import type { Prettify } from "src/types/helpers";
import type { IS_SEPARABLE_KEY, IsSeparable } from "./custom/separable";
import { IS_ABBR_KEY, type IsAbbr } from "./ud/abbr";
import { ANIMACITY_KEY, type Animacy } from "./ud/animacy";
import { ASPECT_KEY, type Aspect } from "./ud/aspect";
import { CASE_KEY, type Case } from "./ud/case";
import { CLUSIVITY_KEY, type Clusivity } from "./ud/clusivity";
import { DEFINITE_KEY, type Definite } from "./ud/definite";
import { DEGREE_KEY, type Degree } from "./ud/degree";
import { DEIXIS_KEY, type Deixis } from "./ud/deixis";
import { DEIXIS_REF_KEY, type DeixisRef } from "./ud/deixis-ref";
import { EVIDENT_KEY, type Evident } from "./ud/evident";
import { EXT_POS_KEY, type ExtPos } from "./ud/ext-pos";
import { IS_FOREIGN_KEY, type IsForeign } from "./ud/foreign";
import { GENDER_KEY, type Gender } from "./ud/gender";
import { MOOD_KEY, type Mood } from "./ud/mood";
import { NOUN_CLASS_KEY, type NounClass } from "./ud/noun-class";
import { NUM_TYPE_KEY, type NumType } from "./ud/num-type";
import { type GrammaticalNumber, NUMBER_KEY } from "./ud/number";
import { PERSON_KEY, type Person } from "./ud/person";
import { POLARITY_KEY, type Polarity } from "./ud/polarity";
import { POLITE_KEY, type Polite } from "./ud/polite";
import { IS_POSS_KEY, type IsPoss } from "./ud/poss";
import { PRON_TYPE_KEY, type PronType } from "./ud/pron-type";
import { IS_REFLEX_KEY, type IsReflex } from "./ud/reflex";
import { TENSE_KEY, type Tense } from "./ud/tense";
import { VERB_FORM_KEY, type VerbForm } from "./ud/verb-form";
import { VOICE_KEY, type Voice } from "./ud/voice";

export type AbstractFeatures = Prettify<{
	[IS_ABBR_KEY]: IsAbbr;
	[ANIMACITY_KEY]: Animacy;
	[ASPECT_KEY]: Aspect;
	[CASE_KEY]: Case;
	[CLUSIVITY_KEY]: Clusivity;
	[DEFINITE_KEY]: Definite;
	[DEGREE_KEY]: Degree;
	[DEIXIS_KEY]: Deixis;
	[DEIXIS_REF_KEY]: DeixisRef;
	[EVIDENT_KEY]: Evident;
	[EXT_POS_KEY]: ExtPos;
	[IS_FOREIGN_KEY]: IsForeign;
	[GENDER_KEY]: Gender;
	[MOOD_KEY]: Mood;
	[NOUN_CLASS_KEY]: NounClass;
	[NUMBER_KEY]: GrammaticalNumber;
	[NUM_TYPE_KEY]: NumType;
	[PERSON_KEY]: Person;
	[POLARITY_KEY]: Polarity;
	[POLITE_KEY]: Polite;
	[IS_POSS_KEY]: IsPoss;
	[PRON_TYPE_KEY]: PronType;
	[IS_REFLEX_KEY]: IsReflex;
	[TENSE_KEY]: Tense;
	[VERB_FORM_KEY]: VerbForm;
	[VOICE_KEY]: Voice;
	[IS_SEPARABLE_KEY]: IsSeparable;
}>;
