export {
	DE_LEMMA_LINGUISTIC_UNITS,
	DE_LEXEM_POS,
	DeLemmaLinguisticUnit,
	DeLemmaLinguisticUnitSchema,
	type DeLemmaResult,
	DeLemmaResultSchema,
	DeLexemLemmaResultSchema,
	type DeLexemPos,
	DeLexemPosSchema,
	DePhrasemLemmaResultSchema,
	type DePosLikeKind,
	DePosLikeKindSchema,
} from "./de-lemma-result";

export {
	type DeEnrichmentInput,
	DeEnrichmentInputSchema,
	type DeEnrichmentOutput,
	DeEnrichmentOutputSchema,
	type DeFeaturesInput,
	DeFeaturesInputSchema,
	type DeFeaturesOutput,
	DeFeaturesOutputSchema,
	type DeInflectionInput,
	DeInflectionInputSchema,
	type DeInflectionOutput,
	DeInflectionOutputSchema,
	DeLexemEnrichmentOutputSchema,
	type DeLexemTarget,
	DeLexemTargetSchema,
	type DeLexicalTarget,
	DeLexicalTargetSchema,
	DePhrasemEnrichmentOutputSchema,
	type DePhrasemTarget,
	DePhrasemTargetSchema,
	type DeRelationInput,
	DeRelationInputSchema,
	type DeRelationOutput,
	DeRelationOutputSchema,
	type DeRelationSubKind,
	DeRelationSubKindSchema,
	type DeWordTranslationInput,
	DeWordTranslationInputSchema,
	type DeWordTranslationOutput,
	DeWordTranslationOutputSchema,
	isDeLexemTarget,
	isDePhrasemTarget,
	toDeLexicalTarget,
} from "./generate-contracts";
