import type {
	LemmaSchemaLanguageShape,
	SelectionSchemaLanguageShape,
} from "../../../registry-shapes";
import {
	EnglishAdjectiveInflectionSelectionSchema,
	EnglishAdjectiveLemmaSchema,
	EnglishAdjectiveLemmaSelectionSchema,
	EnglishAdjectiveStandardPartialSelectionSchema,
	EnglishAdjectiveStandardVariantSelectionSchema,
	EnglishAdjectiveTypoInflectionSelectionSchema,
	EnglishAdjectiveTypoLemmaSelectionSchema,
	EnglishAdjectiveTypoPartialSelectionSchema,
	EnglishAdjectiveTypoVariantSelectionSchema,
} from "./adjective/english-adjective-bundle";
import {
	EnglishAdpositionInflectionSelectionSchema,
	EnglishAdpositionLemmaSchema,
	EnglishAdpositionLemmaSelectionSchema,
	EnglishAdpositionStandardPartialSelectionSchema,
	EnglishAdpositionStandardVariantSelectionSchema,
	EnglishAdpositionTypoInflectionSelectionSchema,
	EnglishAdpositionTypoLemmaSelectionSchema,
	EnglishAdpositionTypoPartialSelectionSchema,
	EnglishAdpositionTypoVariantSelectionSchema,
} from "./adposition/english-adposition-bundle";
import {
	EnglishAdverbInflectionSelectionSchema,
	EnglishAdverbLemmaSchema,
	EnglishAdverbLemmaSelectionSchema,
	EnglishAdverbStandardPartialSelectionSchema,
	EnglishAdverbStandardVariantSelectionSchema,
	EnglishAdverbTypoInflectionSelectionSchema,
	EnglishAdverbTypoLemmaSelectionSchema,
	EnglishAdverbTypoPartialSelectionSchema,
	EnglishAdverbTypoVariantSelectionSchema,
} from "./adverb/english-adverb-bundle";
import {
	EnglishAuxiliaryInflectionSelectionSchema,
	EnglishAuxiliaryLemmaSchema,
	EnglishAuxiliaryLemmaSelectionSchema,
	EnglishAuxiliaryStandardPartialSelectionSchema,
	EnglishAuxiliaryStandardVariantSelectionSchema,
	EnglishAuxiliaryTypoInflectionSelectionSchema,
	EnglishAuxiliaryTypoLemmaSelectionSchema,
	EnglishAuxiliaryTypoPartialSelectionSchema,
	EnglishAuxiliaryTypoVariantSelectionSchema,
} from "./auxiliary/english-auxiliary-bundle";
import {
	EnglishCoordinatingConjunctionInflectionSelectionSchema,
	EnglishCoordinatingConjunctionLemmaSchema,
	EnglishCoordinatingConjunctionLemmaSelectionSchema,
	EnglishCoordinatingConjunctionStandardPartialSelectionSchema,
	EnglishCoordinatingConjunctionStandardVariantSelectionSchema,
	EnglishCoordinatingConjunctionTypoInflectionSelectionSchema,
	EnglishCoordinatingConjunctionTypoLemmaSelectionSchema,
	EnglishCoordinatingConjunctionTypoPartialSelectionSchema,
	EnglishCoordinatingConjunctionTypoVariantSelectionSchema,
} from "./coordinating-conjunction/english-coordinating-conjunction-bundle";
import {
	EnglishDeterminerInflectionSelectionSchema,
	EnglishDeterminerLemmaSchema,
	EnglishDeterminerLemmaSelectionSchema,
	EnglishDeterminerStandardPartialSelectionSchema,
	EnglishDeterminerStandardVariantSelectionSchema,
	EnglishDeterminerTypoInflectionSelectionSchema,
	EnglishDeterminerTypoLemmaSelectionSchema,
	EnglishDeterminerTypoPartialSelectionSchema,
	EnglishDeterminerTypoVariantSelectionSchema,
} from "./determiner/english-determiner-bundle";
import {
	EnglishInterjectionInflectionSelectionSchema,
	EnglishInterjectionLemmaSchema,
	EnglishInterjectionLemmaSelectionSchema,
	EnglishInterjectionStandardPartialSelectionSchema,
	EnglishInterjectionStandardVariantSelectionSchema,
	EnglishInterjectionTypoInflectionSelectionSchema,
	EnglishInterjectionTypoLemmaSelectionSchema,
	EnglishInterjectionTypoPartialSelectionSchema,
	EnglishInterjectionTypoVariantSelectionSchema,
} from "./interjection/english-interjection-bundle";
import {
	EnglishNounInflectionSelectionSchema,
	EnglishNounLemmaSchema,
	EnglishNounLemmaSelectionSchema,
	EnglishNounStandardPartialSelectionSchema,
	EnglishNounStandardVariantSelectionSchema,
	EnglishNounTypoInflectionSelectionSchema,
	EnglishNounTypoLemmaSelectionSchema,
	EnglishNounTypoPartialSelectionSchema,
	EnglishNounTypoVariantSelectionSchema,
} from "./noun/english-noun-bundle";
import {
	EnglishNumeralInflectionSelectionSchema,
	EnglishNumeralLemmaSchema,
	EnglishNumeralLemmaSelectionSchema,
	EnglishNumeralStandardPartialSelectionSchema,
	EnglishNumeralStandardVariantSelectionSchema,
	EnglishNumeralTypoInflectionSelectionSchema,
	EnglishNumeralTypoLemmaSelectionSchema,
	EnglishNumeralTypoPartialSelectionSchema,
	EnglishNumeralTypoVariantSelectionSchema,
} from "./numeral/english-numeral-bundle";
import {
	EnglishOtherInflectionSelectionSchema,
	EnglishOtherLemmaSchema,
	EnglishOtherLemmaSelectionSchema,
	EnglishOtherStandardPartialSelectionSchema,
	EnglishOtherStandardVariantSelectionSchema,
	EnglishOtherTypoInflectionSelectionSchema,
	EnglishOtherTypoLemmaSelectionSchema,
	EnglishOtherTypoPartialSelectionSchema,
	EnglishOtherTypoVariantSelectionSchema,
} from "./other/english-other-bundle";
import {
	EnglishParticleInflectionSelectionSchema,
	EnglishParticleLemmaSchema,
	EnglishParticleLemmaSelectionSchema,
	EnglishParticleStandardPartialSelectionSchema,
	EnglishParticleStandardVariantSelectionSchema,
	EnglishParticleTypoInflectionSelectionSchema,
	EnglishParticleTypoLemmaSelectionSchema,
	EnglishParticleTypoPartialSelectionSchema,
	EnglishParticleTypoVariantSelectionSchema,
} from "./particle/english-particle-bundle";
import {
	EnglishPronounInflectionSelectionSchema,
	EnglishPronounLemmaSchema,
	EnglishPronounLemmaSelectionSchema,
	EnglishPronounStandardPartialSelectionSchema,
	EnglishPronounStandardVariantSelectionSchema,
	EnglishPronounTypoInflectionSelectionSchema,
	EnglishPronounTypoLemmaSelectionSchema,
	EnglishPronounTypoPartialSelectionSchema,
	EnglishPronounTypoVariantSelectionSchema,
} from "./pronoun/english-pronoun-bundle";
import {
	EnglishProperNounInflectionSelectionSchema,
	EnglishProperNounLemmaSchema,
	EnglishProperNounLemmaSelectionSchema,
	EnglishProperNounStandardPartialSelectionSchema,
	EnglishProperNounStandardVariantSelectionSchema,
	EnglishProperNounTypoInflectionSelectionSchema,
	EnglishProperNounTypoLemmaSelectionSchema,
	EnglishProperNounTypoPartialSelectionSchema,
	EnglishProperNounTypoVariantSelectionSchema,
} from "./proper-noun/english-proper-noun-bundle";
import {
	EnglishPunctuationInflectionSelectionSchema,
	EnglishPunctuationLemmaSchema,
	EnglishPunctuationLemmaSelectionSchema,
	EnglishPunctuationStandardPartialSelectionSchema,
	EnglishPunctuationStandardVariantSelectionSchema,
	EnglishPunctuationTypoInflectionSelectionSchema,
	EnglishPunctuationTypoLemmaSelectionSchema,
	EnglishPunctuationTypoPartialSelectionSchema,
	EnglishPunctuationTypoVariantSelectionSchema,
} from "./punctuation/english-punctuation-bundle";
import {
	EnglishSubordinatingConjunctionInflectionSelectionSchema,
	EnglishSubordinatingConjunctionLemmaSchema,
	EnglishSubordinatingConjunctionLemmaSelectionSchema,
	EnglishSubordinatingConjunctionStandardPartialSelectionSchema,
	EnglishSubordinatingConjunctionStandardVariantSelectionSchema,
	EnglishSubordinatingConjunctionTypoInflectionSelectionSchema,
	EnglishSubordinatingConjunctionTypoLemmaSelectionSchema,
	EnglishSubordinatingConjunctionTypoPartialSelectionSchema,
	EnglishSubordinatingConjunctionTypoVariantSelectionSchema,
} from "./subordinating-conjunction/english-subordinating-conjunction-bundle";
import {
	EnglishSymbolInflectionSelectionSchema,
	EnglishSymbolLemmaSchema,
	EnglishSymbolLemmaSelectionSchema,
	EnglishSymbolStandardPartialSelectionSchema,
	EnglishSymbolStandardVariantSelectionSchema,
	EnglishSymbolTypoInflectionSelectionSchema,
	EnglishSymbolTypoLemmaSelectionSchema,
	EnglishSymbolTypoPartialSelectionSchema,
	EnglishSymbolTypoVariantSelectionSchema,
} from "./symbol/english-symbol-bundle";
import {
	EnglishVerbInflectionSelectionSchema,
	EnglishVerbLemmaSchema,
	EnglishVerbLemmaSelectionSchema,
	EnglishVerbStandardPartialSelectionSchema,
	EnglishVerbStandardVariantSelectionSchema,
	EnglishVerbTypoInflectionSelectionSchema,
	EnglishVerbTypoLemmaSelectionSchema,
	EnglishVerbTypoPartialSelectionSchema,
	EnglishVerbTypoVariantSelectionSchema,
} from "./verb/english-verb-bundle";

export const EnglishLexemeLemmaSchemas = {
	ADJ: EnglishAdjectiveLemmaSchema,
	ADP: EnglishAdpositionLemmaSchema,
	ADV: EnglishAdverbLemmaSchema,
	AUX: EnglishAuxiliaryLemmaSchema,
	CCONJ: EnglishCoordinatingConjunctionLemmaSchema,
	DET: EnglishDeterminerLemmaSchema,
	INTJ: EnglishInterjectionLemmaSchema,
	NOUN: EnglishNounLemmaSchema,
	NUM: EnglishNumeralLemmaSchema,
	PART: EnglishParticleLemmaSchema,
	PRON: EnglishPronounLemmaSchema,
	PROPN: EnglishProperNounLemmaSchema,
	PUNCT: EnglishPunctuationLemmaSchema,
	SCONJ: EnglishSubordinatingConjunctionLemmaSchema,
	SYM: EnglishSymbolLemmaSchema,
	VERB: EnglishVerbLemmaSchema,
	X: EnglishOtherLemmaSchema,
} satisfies LemmaSchemaLanguageShape["Lexeme"];

export const EnglishStandardInflectionLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveInflectionSelectionSchema,
	ADP: EnglishAdpositionInflectionSelectionSchema,
	ADV: EnglishAdverbInflectionSelectionSchema,
	AUX: EnglishAuxiliaryInflectionSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionInflectionSelectionSchema,
	DET: EnglishDeterminerInflectionSelectionSchema,
	INTJ: EnglishInterjectionInflectionSelectionSchema,
	NOUN: EnglishNounInflectionSelectionSchema,
	NUM: EnglishNumeralInflectionSelectionSchema,
	PART: EnglishParticleInflectionSelectionSchema,
	PRON: EnglishPronounInflectionSelectionSchema,
	PROPN: EnglishProperNounInflectionSelectionSchema,
	PUNCT: EnglishPunctuationInflectionSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionInflectionSelectionSchema,
	SYM: EnglishSymbolInflectionSelectionSchema,
	VERB: EnglishVerbInflectionSelectionSchema,
	X: EnglishOtherInflectionSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Inflection"]["Lexeme"];

export const EnglishStandardLemmaLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveLemmaSelectionSchema,
	ADP: EnglishAdpositionLemmaSelectionSchema,
	ADV: EnglishAdverbLemmaSelectionSchema,
	AUX: EnglishAuxiliaryLemmaSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionLemmaSelectionSchema,
	DET: EnglishDeterminerLemmaSelectionSchema,
	INTJ: EnglishInterjectionLemmaSelectionSchema,
	NOUN: EnglishNounLemmaSelectionSchema,
	NUM: EnglishNumeralLemmaSelectionSchema,
	PART: EnglishParticleLemmaSelectionSchema,
	PRON: EnglishPronounLemmaSelectionSchema,
	PROPN: EnglishProperNounLemmaSelectionSchema,
	PUNCT: EnglishPunctuationLemmaSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionLemmaSelectionSchema,
	SYM: EnglishSymbolLemmaSelectionSchema,
	VERB: EnglishVerbLemmaSelectionSchema,
	X: EnglishOtherLemmaSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Lemma"]["Lexeme"];

export const EnglishStandardPartialLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveStandardPartialSelectionSchema,
	ADP: EnglishAdpositionStandardPartialSelectionSchema,
	ADV: EnglishAdverbStandardPartialSelectionSchema,
	AUX: EnglishAuxiliaryStandardPartialSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionStandardPartialSelectionSchema,
	DET: EnglishDeterminerStandardPartialSelectionSchema,
	INTJ: EnglishInterjectionStandardPartialSelectionSchema,
	NOUN: EnglishNounStandardPartialSelectionSchema,
	NUM: EnglishNumeralStandardPartialSelectionSchema,
	PART: EnglishParticleStandardPartialSelectionSchema,
	PRON: EnglishPronounStandardPartialSelectionSchema,
	PROPN: EnglishProperNounStandardPartialSelectionSchema,
	PUNCT: EnglishPunctuationStandardPartialSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionStandardPartialSelectionSchema,
	SYM: EnglishSymbolStandardPartialSelectionSchema,
	VERB: EnglishVerbStandardPartialSelectionSchema,
	X: EnglishOtherStandardPartialSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Partial"]["Lexeme"];

export const EnglishStandardVariantLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveStandardVariantSelectionSchema,
	ADP: EnglishAdpositionStandardVariantSelectionSchema,
	ADV: EnglishAdverbStandardVariantSelectionSchema,
	AUX: EnglishAuxiliaryStandardVariantSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionStandardVariantSelectionSchema,
	DET: EnglishDeterminerStandardVariantSelectionSchema,
	INTJ: EnglishInterjectionStandardVariantSelectionSchema,
	NOUN: EnglishNounStandardVariantSelectionSchema,
	NUM: EnglishNumeralStandardVariantSelectionSchema,
	PART: EnglishParticleStandardVariantSelectionSchema,
	PRON: EnglishPronounStandardVariantSelectionSchema,
	PROPN: EnglishProperNounStandardVariantSelectionSchema,
	PUNCT: EnglishPunctuationStandardVariantSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionStandardVariantSelectionSchema,
	SYM: EnglishSymbolStandardVariantSelectionSchema,
	VERB: EnglishVerbStandardVariantSelectionSchema,
	X: EnglishOtherStandardVariantSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Standard"]["Variant"]["Lexeme"];

export const EnglishTypoInflectionLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveTypoInflectionSelectionSchema,
	ADP: EnglishAdpositionTypoInflectionSelectionSchema,
	ADV: EnglishAdverbTypoInflectionSelectionSchema,
	AUX: EnglishAuxiliaryTypoInflectionSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionTypoInflectionSelectionSchema,
	DET: EnglishDeterminerTypoInflectionSelectionSchema,
	INTJ: EnglishInterjectionTypoInflectionSelectionSchema,
	NOUN: EnglishNounTypoInflectionSelectionSchema,
	NUM: EnglishNumeralTypoInflectionSelectionSchema,
	PART: EnglishParticleTypoInflectionSelectionSchema,
	PRON: EnglishPronounTypoInflectionSelectionSchema,
	PROPN: EnglishProperNounTypoInflectionSelectionSchema,
	PUNCT: EnglishPunctuationTypoInflectionSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionTypoInflectionSelectionSchema,
	SYM: EnglishSymbolTypoInflectionSelectionSchema,
	VERB: EnglishVerbTypoInflectionSelectionSchema,
	X: EnglishOtherTypoInflectionSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Inflection"]["Lexeme"];

export const EnglishTypoLemmaLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveTypoLemmaSelectionSchema,
	ADP: EnglishAdpositionTypoLemmaSelectionSchema,
	ADV: EnglishAdverbTypoLemmaSelectionSchema,
	AUX: EnglishAuxiliaryTypoLemmaSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionTypoLemmaSelectionSchema,
	DET: EnglishDeterminerTypoLemmaSelectionSchema,
	INTJ: EnglishInterjectionTypoLemmaSelectionSchema,
	NOUN: EnglishNounTypoLemmaSelectionSchema,
	NUM: EnglishNumeralTypoLemmaSelectionSchema,
	PART: EnglishParticleTypoLemmaSelectionSchema,
	PRON: EnglishPronounTypoLemmaSelectionSchema,
	PROPN: EnglishProperNounTypoLemmaSelectionSchema,
	PUNCT: EnglishPunctuationTypoLemmaSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionTypoLemmaSelectionSchema,
	SYM: EnglishSymbolTypoLemmaSelectionSchema,
	VERB: EnglishVerbTypoLemmaSelectionSchema,
	X: EnglishOtherTypoLemmaSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Lemma"]["Lexeme"];

export const EnglishTypoPartialLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveTypoPartialSelectionSchema,
	ADP: EnglishAdpositionTypoPartialSelectionSchema,
	ADV: EnglishAdverbTypoPartialSelectionSchema,
	AUX: EnglishAuxiliaryTypoPartialSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionTypoPartialSelectionSchema,
	DET: EnglishDeterminerTypoPartialSelectionSchema,
	INTJ: EnglishInterjectionTypoPartialSelectionSchema,
	NOUN: EnglishNounTypoPartialSelectionSchema,
	NUM: EnglishNumeralTypoPartialSelectionSchema,
	PART: EnglishParticleTypoPartialSelectionSchema,
	PRON: EnglishPronounTypoPartialSelectionSchema,
	PROPN: EnglishProperNounTypoPartialSelectionSchema,
	PUNCT: EnglishPunctuationTypoPartialSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionTypoPartialSelectionSchema,
	SYM: EnglishSymbolTypoPartialSelectionSchema,
	VERB: EnglishVerbTypoPartialSelectionSchema,
	X: EnglishOtherTypoPartialSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Partial"]["Lexeme"];

export const EnglishTypoVariantLexemeSelectionSchemas = {
	ADJ: EnglishAdjectiveTypoVariantSelectionSchema,
	ADP: EnglishAdpositionTypoVariantSelectionSchema,
	ADV: EnglishAdverbTypoVariantSelectionSchema,
	AUX: EnglishAuxiliaryTypoVariantSelectionSchema,
	CCONJ: EnglishCoordinatingConjunctionTypoVariantSelectionSchema,
	DET: EnglishDeterminerTypoVariantSelectionSchema,
	INTJ: EnglishInterjectionTypoVariantSelectionSchema,
	NOUN: EnglishNounTypoVariantSelectionSchema,
	NUM: EnglishNumeralTypoVariantSelectionSchema,
	PART: EnglishParticleTypoVariantSelectionSchema,
	PRON: EnglishPronounTypoVariantSelectionSchema,
	PROPN: EnglishProperNounTypoVariantSelectionSchema,
	PUNCT: EnglishPunctuationTypoVariantSelectionSchema,
	SCONJ: EnglishSubordinatingConjunctionTypoVariantSelectionSchema,
	SYM: EnglishSymbolTypoVariantSelectionSchema,
	VERB: EnglishVerbTypoVariantSelectionSchema,
	X: EnglishOtherTypoVariantSelectionSchema,
} satisfies SelectionSchemaLanguageShape["Typo"]["Variant"]["Lexeme"];
