export { createLexicalGenerationModule } from "./create-lexical-generation-module";
export type { LexicalGenerationError } from "./errors";
export {
	LexicalGenerationFailureKind,
	lexicalGenerationError,
} from "./errors";
export {
	createLexicalMeta,
	createMetaTagFromResolvedLemma,
} from "./lexical-meta";
export type {
	CreateLexicalGenerationModuleParams,
	GenerateLexicalInfoOptions,
	LemmaGenerator,
	LexemFeatures,
	LexemInflections,
	LexicalAdjectiveClassification,
	LexicalAdjectiveDistribution,
	LexicalAdjectiveGovernedPattern,
	LexicalAdjectiveGradability,
	LexicalAdjectiveValency,
	LexicalCase,
	LexicalCore,
	LexicalGenerationModule,
	LexicalGenus,
	LexicalInflectionForm,
	LexicalInfo,
	LexicalInfoField,
	LexicalInfoGenerator,
	LexicalMeta,
	LexicalMorpheme,
	LexicalMorphemeKind,
	LexicalNounClass,
	LexicalNounIdentity,
	LexicalNumber,
	LexicalPhrasemeKind,
	LexicalPos,
	LexicalRelationKind,
	LexicalRelations,
	LexicalSurfaceKind,
	LexicalVerbConjugation,
	LexicalVerbReflexivity,
	LexicalVerbSeparability,
	LexicalVerbValency,
	MorphemicBreakdown,
	PhrasemFeatures,
	ResolvedLemma,
	SenseDisambiguator,
	SenseMatchResult,
	StructuredFetchFn,
	ZodSchemaLike,
} from "./public-types";
export type { LexicalGenerationSettings } from "./settings";
