import type { Prettify } from "../../../../../../../../types/helpers";
import type { GovernedPreposition } from "./custom/governed-preposition";
import type { IsPhrasal } from "./custom/is-phrasal";
import type { IsSeparable } from "./custom/separable";
import type { IsAbbr } from "./ud/abbr";
import type { Animacy } from "./ud/animacy";
import type { Aspect } from "./ud/aspect";
import type { Case } from "./ud/case";
import type { Clusivity } from "./ud/clusivity";
import type { Definite } from "./ud/definite";
import type { Degree } from "./ud/degree";
import type { Deixis } from "./ud/deixis";
import type { DeixisRef } from "./ud/deixis-ref";
import type { Evident } from "./ud/evident";
import type { ExtPos } from "./ud/ext-pos";
import type { IsForeign } from "./ud/foreign";
import type { Gender } from "./ud/gender";
import type { Mood } from "./ud/mood";
import type { NounClass } from "./ud/noun-class";
import type { NumType } from "./ud/num-type";
import type { GrammaticalNumber } from "./ud/number";
import type { Person } from "./ud/person";
import type { Polarity } from "./ud/polarity";
import type { Polite } from "./ud/polite";
import type { IsPoss } from "./ud/poss";
import type { PronType } from "./ud/pron-type";
import type { IsReflex } from "./ud/reflex";
import type { Tense } from "./ud/tense";
import type { VerbForm } from "./ud/verb-form";
import type { Voice } from "./ud/voice";

export type AbstractFeatures = Prettify<{
	abbr: IsAbbr;
	animacy: Animacy;
	aspect: Aspect;
	case: Case;
	clusivity: Clusivity;
	definite: Definite;
	degree: Degree;
	deixis: Deixis;
	deixisRef: DeixisRef;
	evident: Evident;
	extPos: ExtPos;
	foreign: IsForeign;
	gender: Gender;
	governedPreposition: GovernedPreposition;
	isPhrasal: IsPhrasal;
	mood: Mood;
	nounClass: NounClass;
	number: GrammaticalNumber;
	numType: NumType;
	person: Person;
	polarity: Polarity;
	polite: Polite;
	poss: IsPoss;
	pronType: PronType;
	reflex: IsReflex;
	tense: Tense;
	verbForm: VerbForm;
	voice: Voice;
	separable: IsSeparable;
}>;
